### ISSUE TITLE
The registration is successful but the login is not available on the website

### ISSUE THREAD

**Issue by HiZhaoYun** [critesjosh/aztec-sdk-starter#6]
I used the RPC of the main network and specified the alias. The transaction was successful, but I could not log in on the website.

The error is : Incorrect alias

But I'm sure the alias is right.

**Comment by critesjosh** [comment]
Did you resolve this?

**Comment by Yakim12** [comment]
please help, I had the same problem
i can‘t sign in website with alias,my alias:m6QzN8
register txId 0xa81c3b3f249786e777fd7de509d98a1f9cc717b871d6029b9e11cec776e7abef

**Comment by critesjosh** [comment]
@Yakim12 is this a problem with logging into zk.money?

**Comment by Yakim12** [comment]
> @Yakim12 is this a problem with logging into zk.money?

yes， error is : Incorrect alias
