### ISSUE TITLE
no exported member 'ChainProperties'.

### ISSUE THREAD

**Issue by yakimzhang** [critesjosh/aztec-sdk-starter#8]
when  yarn run got this error:

src/latest/defiAdaptors/elementAdaptor.ts:4:5 - error TS2305: Module '"@aztec/bridge-clients/client-dest/src/client/element/element-bridge-data"' has no exported member 'ChainProperties'.

**Comment by critesjosh** [comment]
i just pushed some updates to this repo, it should work now
